variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "private_app_subnet_az1_cidr" {}
variable "private_app_subnet_az2_cidr" {}
variable "private_data_subnet_az1_cidr" {}
variable "private_data_subnet_az2_cidr" {}
variable "ami" {}
variable "instance_size" {}
variable "engine_name" {}
variable "engine_version" {}
variable "instance_type" {}
variable "availability_zone" {}
variable "user_name" {}
variable "passwd" {}
variable "environment" {}
